.PHONY: clean All

All:
	@echo "----------Building project:[ ax329x_sdk - Debug ]----------"
	@$(MAKE) -f  "ax329x_sdk.mk" PreBuild && $(MAKE) -f  "ax329x_sdk.mk" && $(MAKE) -f  "ax329x_sdk.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ ax329x_sdk - Debug ]----------"
	@$(MAKE) -f  "ax329x_sdk.mk" clean
