/****************************************************************************
**
 **                              LAYOUT
  ** *   **             THE APPOTECH MULTIMEDIA PROCESSOR
   **** **                  LAYOUT FOR SETTING MENU
  *** ***
 **  * **               (C) COPYRIGHT 2016 BUILDWIN 
**      **                         
         **         BuildWin SZ LTD.CO  ; VIDEO PROJECT TEAM
          **   
* File Name   : menu_setting.c
* Author      : Mark.Douglas 
* Version     : V100
* Date        : 09/22/2016
* Description : 
*               
* History     : 
* 2016-09-22  : 
*      <1>.This is created by mark,set version as v100.
*      <2>.Add basic functions & information
******************************************************************************/
#include "application.h"
#include "uiWin.h"
#include "menu.h"

extern char version_str[32];

MENU_OPTION_START(vidResolution)//---------video resolution
MENU_OPTION_STR(R_ID_STR_RES_FHD)
MENU_OPTION_STR(R_ID_STR_RES_HD)
MENU_OPTION_END()

MENU_OPTION_START(CapturePrint)//---------print En
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_ON)
MENU_OPTION_END()

MENU_OPTION_START(photoResolution)//--------- photo resolution
MENU_OPTION_STR(R_ID_STR_RES_1M)
MENU_OPTION_STR(R_ID_STR_RES_3M)
MENU_OPTION_STR(R_ID_STR_RES_5M)
MENU_OPTION_STR(R_ID_STR_RES_8M)
MENU_OPTION_STR(R_ID_STR_RES_12M)
MENU_OPTION_STR(R_ID_STR_RES_20M)
MENU_OPTION_STR(R_ID_STR_RES_48M)
MENU_OPTION_END()

MENU_OPTION_START(loopRecord)//--------loop record
//MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_TIM_3MIN)
MENU_OPTION_STR(R_ID_STR_TIM_5MIN)
MENU_OPTION_STR(R_ID_STR_TIM_10MIN)
MENU_OPTION_END()

#if defined(USB_PWM_LCDBK)
MENU_OPTION_START(brightness)		//----vol level
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_1)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_2)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_3)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_4)
MENU_OPTION_END()
#endif

/*
MENU_OPTION_START(awb)//---------white balance
MENU_OPTION_STR(R_ID_STR_ISP_AUTO)
MENU_OPTION_STR(R_ID_STR_ISP_SUNLIGHT)
MENU_OPTION_STR(R_ID_STR_ISP_CLOUDY)
MENU_OPTION_STR(R_ID_STR_ISP_TUNGSTEN)
MENU_OPTION_STR(R_ID_STR_ISP_FLUORESCENT)
MENU_OPTION_END()

MENU_OPTION_START(ev)//--------EV
MENU_OPTION_STR(R_ID_STR_COM_P2_0)
MENU_OPTION_STR(R_ID_STR_COM_P1_0)
MENU_OPTION_STR(R_ID_STR_COM_P0_0)
MENU_OPTION_STR(R_ID_STR_COM_N1_0)
MENU_OPTION_STR(R_ID_STR_COM_N2_0)
MENU_OPTION_END()

MENU_OPTION_START(md)//--------motion decetion
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_ON)
MENU_OPTION_END()

MENU_OPTION_START(audio)//--------movie audio
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_ON)
MENU_OPTION_END()

MENU_OPTION_START(parking)//--------parking mode
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_ON)
MENU_OPTION_END()



MENU_OPTION_START(gsensor)//--------gsensor
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_LOW)
MENU_OPTION_STR(R_ID_STR_COM_MIDDLE)
MENU_OPTION_STR(R_ID_STR_COM_HIGH)
MENU_OPTION_END()
*/

MENU_OPTION_START(keySound)//--------key sound
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_ON)
MENU_OPTION_END()


MENU_OPTION_START(autoPowerOff)//----AUTO POWER OFF
//MENU_OPTION_STR(R_ID_STR_TIM_1MIN)
MENU_OPTION_STR(R_ID_STR_TIM_3MIN)
MENU_OPTION_STR(R_ID_STR_TIM_5MIN)
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_END()

MENU_OPTION_START(language)//--------LANGUAGE
#ifdef USE_KOERA_UI
//MENU_OPTION_STR(R_ID_STR_LAN_SCHINESE)
MENU_OPTION_STR(R_ID_STR_LAN_KOERA)
MENU_OPTION_STR(R_ID_STR_LAN_JAPANESE)
MENU_OPTION_STR(R_ID_STR_LAN_ENGLISH)
#elif defined(USE_CZECH_LANGUAGE)
MENU_OPTION_STR(R_ID_STR_LAN_ENGLISH)
MENU_OPTION_STR(R_ID_STR_LAN_CZECH)
MENU_OPTION_STR(R_ID_STR_LAN_SLOVAK)
MENU_OPTION_STR(R_ID_STR_LAN_GERMAN)
MENU_OPTION_STR(R_ID_STR_LAN_POLISH)
MENU_OPTION_STR(R_ID_STR_LAN_HUNGARIAN)
#elif defined(USE_THREE_LANUGAE)
MENU_OPTION_STR(R_ID_STR_LAN_ENGLISH)
MENU_OPTION_STR(R_ID_STR_LAN_HEBREW)
MENU_OPTION_STR(R_ID_STR_LAN_ARABIC)
#elif defined(USE_DIE_MAUS_UI)
MENU_OPTION_STR(R_ID_STR_LAN_ENGLISH)
MENU_OPTION_STR(R_ID_STR_LAN_SPANISH)
MENU_OPTION_STR(R_ID_STR_LAN_GERMAN)
MENU_OPTION_STR(R_ID_STR_LAN_FRECH)
MENU_OPTION_STR(R_ID_STR_LAN_DUTCH)
#else
MENU_OPTION_STR(R_ID_STR_LAN_ENGLISH)
MENU_OPTION_STR(R_ID_STR_LAN_SCHINESE)
MENU_OPTION_STR(R_ID_STR_LAN_TCHINESE)
MENU_OPTION_STR(R_ID_STR_LAN_JAPANESE)
MENU_OPTION_STR(R_ID_STR_LAN_KOERA)
MENU_OPTION_STR(R_ID_STR_LAN_RUSSIAN)
MENU_OPTION_STR(R_ID_STR_LAN_FRECH)
MENU_OPTION_STR(R_ID_STR_LAN_GERMAN)
MENU_OPTION_STR(R_ID_STR_LAN_CZECH)
MENU_OPTION_STR(R_ID_STR_LAN_PORTUGUESE)
MENU_OPTION_STR(R_ID_STR_LAN_POLISH)
MENU_OPTION_STR(R_ID_STR_LAN_DUTCH)
MENU_OPTION_STR(R_ID_STR_LAN_TURKEY)
MENU_OPTION_STR(R_ID_STR_LAN_TAI)
MENU_OPTION_STR(R_ID_STR_LAN_SPANISH)
MENU_OPTION_STR(R_ID_STR_LAN_HEBREW)
MENU_OPTION_STR(R_ID_STR_LAN_ITALIAN)
#if defined(USE_BOARD_DY43)
MENU_OPTION_STR(R_ID_STR_LAN_SWEDISH)   //瑞典语 
MENU_OPTION_STR(R_ID_STR_LAN_DANISH)    //丹麦语
MENU_OPTION_STR(R_ID_STR_LAN_HUNGARIAN) //匈牙利语
MENU_OPTION_STR(R_ID_STR_LAN_GREEK)     //希腊语
#endif
MENU_OPTION_STR(R_ID_STR_LAN_ARABIC)
#endif
MENU_OPTION_END()

#ifdef USB_TIMEMOREPHOTO_INSETTING
MENU_OPTION_START(timephoto)		//----timed photo
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_TIM_3SEC)
MENU_OPTION_STR(R_ID_STR_TIM_5SEC)
MENU_OPTION_STR(R_ID_STR_TIM_10SEC)
MENU_OPTION_END()

MENU_OPTION_START(morephoto)		//----more photo
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_PHOTO_NUM_3)
MENU_OPTION_STR(R_ID_STR_PHOTO_NUM_5)
MENU_OPTION_END()
#endif
#if 1//defined(USE_BOARD_DY43)||defined(USE_BOARD_DY151)
MENU_OPTION_START(timephoto)		//----timed photo
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_TIM_3SEC)
MENU_OPTION_STR(R_ID_STR_TIM_5SEC)
MENU_OPTION_STR(R_ID_STR_TIM_10SEC)
MENU_OPTION_END()
#endif

#if defined(USE_BOARD_DY05)||defined(USE_BOARD_DY20)||defined(USE_BOARD_DY26)
MENU_OPTION_START(vol)		//----vol level
//MENU_OPTION_STR(R_ID_STR_COM_OFF)
//MENU_OPTION_STR(R_ID_STR_COM_LOW)
//MENU_OPTION_STR(R_ID_STR_COM_MIDDLE)
//MENU_OPTION_STR(R_ID_STR_COM_HIGH)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_1)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_2)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_3)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_4)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_5)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_6)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_7)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_8)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_9)
MENU_OPTION_STR(R_ID_STR_VOL_LEVEL_10)
MENU_OPTION_END()
#endif

MENU_OPTION_START(printdensity)		//----print density
MENU_OPTION_STR(R_ID_STR_COM_LEVEL_1)
MENU_OPTION_STR(R_ID_STR_COM_LEVEL_2)
MENU_OPTION_STR(R_ID_STR_COM_LEVEL_3)
MENU_OPTION_STR(R_ID_STR_COM_LEVEL_4)
MENU_OPTION_STR(R_ID_STR_COM_LEVEL_5)
MENU_OPTION_STR(R_ID_STR_COM_LEVEL_6)
MENU_OPTION_STR(R_ID_STR_COM_LEVEL_7)
MENU_OPTION_END()

MENU_OPTION_START(printdensitymode)		//----print mode
MENU_OPTION_STR(R_ID_STR_SET_PRINT_DOT)
MENU_OPTION_STR(R_ID_STR_SET_PRINT_GRAY)
MENU_OPTION_END()


MENU_OPTION_START(timeStamp)//--------time stamp
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_ON)
MENU_OPTION_END()

/*
MENU_OPTION_START(frequency)
MENU_OPTION_STR(R_ID_STR_COM_50HZ)
MENU_OPTION_STR(R_ID_STR_COM_60HZ)
MENU_OPTION_END()
*/
MENU_OPTION_START(irLed)//--------ir
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_COM_ON)
//MENU_OPTION_STR(R_ID_STR_COM_ALWAYSON)
MENU_OPTION_END()

MENU_OPTION_START(flashset)//--------flash
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_ISP_AUTO)//自动拍闪
//MENU_OPTION_STR(R_ID_STR_COM_LIGHTING_FORM)//常亮
MENU_OPTION_END()

#ifdef USE_STICKER_PRTPAPER
MENU_OPTION_START(printtype)		//----print mode
MENU_OPTION_STR(R_ID_STR_PRINT_PT_PAPER)
MENU_OPTION_STR(R_ID_STR_PRINT_BGJ_PAPER)
MENU_OPTION_END()
#endif
#ifdef ADD_PRINT_PAPER_TYPE
MENU_OPTION_START(printtype)		//----print mode
MENU_OPTION_STR(R_ID_STR_PRINT_BW_PAPER)
MENU_OPTION_STR(R_ID_STR_PRINT_COL_PAPER)
MENU_OPTION_END()
#endif

MENU_OPTION_START(version)
MENU_OPTION_STR("JRX_20220309")
MENU_OPTION_END()


MENU_OPTION_START(screenSave)//--------screen Save
MENU_OPTION_STR(R_ID_STR_COM_OFF)
MENU_OPTION_STR(R_ID_STR_TIM_1MIN)
//MENU_OPTION_STR(R_ID_STR_TIM_2MIN)
MENU_OPTION_STR(R_ID_STR_TIM_3MIN)
MENU_OPTION_STR(R_ID_STR_TIM_5MIN)
//MENU_OPTION_STR(R_ID_STR_TIM_10MIN)
MENU_OPTION_END()

void menuProcDateTime(winHandle handle,uint32 parameNum,uint32* parame);
void menuProcFormat(winHandle handle,uint32 parameNum,uint32* parame);
void menuProcDefault(winHandle handle,uint32 parameNum,uint32* parame);
void menuProcVersion(winHandle handle,uint32 parameNum,uint32* parame);

MENU_ITME_START(movie)
//#if (1 == IR_MENU_EN)
//MENU_ITEM_OPTIONS(irLed,CONFIG_ID_IR_LED,R_ID_ICON_MENULIGHTNORMAL,R_ID_STR_SET_FILLIGHT)
//#endif
#ifndef USE_BOARD_DY45
#if defined(USE_BT_CONTROL_LED)||defined(USE_5050IC_CONTROL_LED)||defined(USE_GPIO_CONTROL_LED) ////#if (1 == IR_MENU_EN)
MENU_ITEM_OPTIONS(irLed,CONFIG_ID_IR_LED,R_ID_ICON_MENULIGHTNORMAL,R_ID_STR_SET_FILLIGHT)
#endif 
#endif

#if defined(USE_BOARD_DY16)||defined(USE_BOARD_DY79)||defined(USE_BOARD_J589)||defined(USE_BOARD_DY116)||defined(USE_BOARD_DY43)||defined(USE_BOARD_DY152)
MENU_ITEM_OPTIONS(CapturePrint,	CONFIG_ID_PRINTER_EN,R_ID_ICON_MENUSTRAMP,R_ID_STR_CAP_PRINT)
#endif

#ifdef ADD_PRINT_PAPER_TYPE
MENU_ITEM_OPTIONS(printtype,CONFIG_ID_PRINTER_TYPE2,R_ID_ICON_MENUPRINTDENSITY,R_ID_STR_PRINT_TYPE_PAPER)
#endif

MENU_ITEM_OPTIONS(printdensity,CONFIG_ID_PRINTER_DENSITY,R_ID_ICON_MENUPRINTDENSITY,R_ID_STR_SET_PRINT_DENSITY)
MENU_ITEM_OPTIONS(printdensitymode,CONFIG_ID_PRINTER_MODE,R_ID_ICON_MENUPRINTDENSITY,R_ID_STR_SET_PRINT_MODE)

#ifdef USE_STICKER_PRTPAPER
MENU_ITEM_OPTIONS(printtype,CONFIG_ID_PRINTER_TYPE,R_ID_ICON_MENUPRINTDENSITY,R_ID_STR_PRINT_TYPE_PAPER)
#endif

MENU_ITEM_OPTIONS(photoResolution,CONFIG_ID_PRESLUTION,R_ID_ICON_MENUIMAGEQ,R_ID_STR_SET_QUALITY)

#if defined(USE_BOARD_DY43)||defined(USE_BOARD_DY152)
MENU_ITEM_OPTIONS(timephoto,CONFIG_ID_TIMEPHOTO,R_ID_ICON_MENUCLOCK,R_ID_STR_SET_TIMEPHOTO)
#endif

#ifdef USB_TIMEMOREPHOTO_INSETTING
MENU_ITEM_OPTIONS(morephoto,CONFIG_ID_MOREPHOTO,R_ID_ICON_MENUMOREPHOTO,R_ID_STR_SET_MOREPHOTO)
MENU_ITEM_OPTIONS(timephoto,CONFIG_ID_TIMEPHOTO,R_ID_ICON_MENUCLOCK,R_ID_STR_SET_TIMEPHOTO)
#endif
#if defined(USE_FLASH_SET)||defined(USE_BOARD_DY152) 
MENU_ITEM_OPTIONS(flashset,CONFIG_ID_CAP_FLASH,R_ID_ICON_MENULIGHTNORMAL,R_ID_STR_SET_FILLIGHT)
#endif

MENU_ITEM_OPTIONS(vidResolution,CONFIG_ID_RESOLUTION,R_ID_ICON_MENURESOLUTION,R_ID_STR_SET_VIDEO_RESOLUTION)
MENU_ITEM_OPTIONS(timeStamp,CONFIG_ID_TIMESTAMP,R_ID_ICON_MENUSTRAMP,R_ID_STR_SET_TIMESTRAMP)
MENU_ITEM_OPTIONS(language,CONFIG_ID_LANGUAGE,R_ID_ICON_MENULANGUAGE,R_ID_STR_SET_LANGUAGE)
//MENU_ITEM_OPTIONS(loopRecord,CONFIG_ID_LOOPTIME,R_ID_ICON_MENULOOPRECORD,R_ID_STR_SET_LOOPRECORD)
//MENU_ITEM_OPTIONS(awb,CONFIG_ID_WBLANCE,R_ID_ICON_MENULIGHTNORMAL,R_ID_STR_ISP_WHITEBL)
//MENU_ITEM_OPTIONS(ev,CONFIG_ID_EV,R_ID_ICON_MENUEV,R_ID_STR_ISP_EXPOSURE)
//MENU_ITEM_OPTIONS(md,CONFIG_ID_MOTIONDECTION,R_ID_ICON_MENUMOTION,R_ID_STR_SET_MOTIONDET)
//MENU_ITEM_OPTIONS(audio,CONFIG_ID_AUDIOREC,R_ID_ICON_MENUAUDIO,R_ID_STR_SET_AUDIOREC)
//MENU_ITEM_OPTIONS(parking,CONFIG_ID_PARKMODE,R_ID_ICON_MENUMONITOR,R_ID_STR_SET_PARKMODE)
//MENU_ITEM_OPTIONS(gsensor,CONFIG_ID_GSENSOR,R_ID_ICON_MENUGSENSOR,R_ID_STR_SET_GSENSOR)
#if !defined(USE_BOARD_DY20)&&!defined(USE_BOARD_DY05)&&!defined(USE_BOARD_DY26)
MENU_ITEM_OPTIONS(keySound,CONFIG_ID_KEYSOUND,R_ID_ICON_MENUAUDIO,R_ID_STR_SET_BEEPSOUND)
#endif
#if defined(USE_BOARD_DY20)||defined(USE_BOARD_DY05)||defined(USE_BOARD_DY26)
MENU_ITEM_OPTIONS(loopRecord,CONFIG_ID_LOOPTIME,R_ID_ICON_MENULOOPRECORD,R_ID_STR_SET_RECORDTIME)//R_ID_STR_SET_LOOPRECORD
MENU_ITEM_OPTIONS(vol,CONFIG_ID_VOLUME,R_ID_ICON_MENUVOLUME,R_ID_STR_SET_VOLUME)
#endif
//MENU_ITEM_OPTIONS(frequency,CONFIG_ID_FREQUNCY,R_ID_ICON_MENUHZ,R_ID_STR_SET_FREQUENCY)
#if defined(USB_PWM_LCDBK)
MENU_ITEM_OPTIONS(brightness,CONFIG_ID_LCD_BRIGHTNESS,R_ID_ICON_MENULIGHTNORMAL,R_ID_STR_SET_BRILEVEL)
#endif
MENU_ITEM_OPTIONS(screenSave,CONFIG_ID_SCREENSAVE,R_ID_ICON_MENUSCRENNOFF,R_ID_STR_SET_SCREEN_SAVERS)
MENU_ITEM_OPTIONS(autoPowerOff,CONFIG_ID_AUTOOFF,R_ID_ICON_MENUSCRENNOFF,R_ID_STR_SET_AUTOOFF)
MENU_ITEM_PROC(menuProcFormat,R_ID_ICON_MENUFORMAT,R_ID_STR_SET_FORMAT)
MENU_ITEM_PROC(menuProcDateTime,R_ID_ICON_MENUCLOCK,R_ID_STR_SET_DATETIME)
MENU_ITEM_PROC(menuProcDefault,R_ID_ICON_MENURESET,R_ID_STR_SET_DEFAULT_SETTING)
//#if SMALL_PANEL_SUPPORT==0
//MENU_ITEM_NO_ID(version,R_ID_ICON_MENUVERSION,R_ID_STR_SET_VERSION)
//#else 
MENU_ITEM_PROC(menuProcVersion,R_ID_ICON_MENUVERSION,R_ID_STR_SET_VERSION)
//#endif
MENU_ITME_END()


MENU_PAGE_START(movie)
MENU_PAGE_ITEMS(movie,R_ID_ICON_MTRECORD,R_ID_ICON_MTRECORD,R_ID_STR_SET_VIDEO)
MENU_PAGE_END()

MENU_DEFINE(movie)

#if 0
static void nouse(void)
{
}
#endif


void menuProcDateTime(winHandle handle,uint32 parameNum,uint32* parame)
{
	uiOpenWindow(&dateTimeWindow,0);
//	uiOpenWindow(&menudatetimeWindow,0);
}
void menuProcFormat(winHandle handle,uint32 parameNum,uint32* parame)
{
	uiOpenWindow(&formatWindow,0);
}
void menuProcDefault(winHandle handle,uint32 parameNum,uint32* parame)
{
	uiOpenWindow(&defaultWindow,0);
}

//#if SMALL_PANEL_SUPPORT>0
void menuProcVersion(winHandle handle,uint32 parameNum,uint32* parame)
{
	uiOpenWindow(&versionWindow,0);
}
//#endif


